package request

import "lending-hub-service/internal/adapter/lazypay/dto/common"

// LPRefundRequest matches Lazypay POST /api/lazypay/v0/refund
type LPRefundRequest struct {
	MerchantTxnID string          `json:"merchantTxnId"` // original order merchantTxnId
	Amount        common.LPAmount `json:"amount"`
	RefundTxnID   string          `json:"refundTxnId"`   // generated by idgen.RefundID()
}
